ALTER TABLE `sunlight_user_group`
    CHANGE COLUMN `adminintersection` `admingroup` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminfman` `fileaccess` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminfmanlimit` `fileglobalaccess` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminneedconfirm` `adminautoconfirm` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `selfdestruction` `selfremove` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminfmanplus` `fileadminaccess` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `sunlight_user_group`
    CHANGE COLUMN `title` `title` VARCHAR(128) COLLATE utf8mb4_unicode_ci NOT NULL,
    CHANGE COLUMN `descr` `descr` VARCHAR(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    CHANGE COLUMN `level` `level` INT(11) NOT NULL DEFAULT 0,
    CHANGE COLUMN `icon` `icon` VARCHAR(16) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    CHANGE COLUMN `blocked` `blocked` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `reglist` `reglist` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `administration` `administration` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminsettings` `adminsettings` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `adminplugins` TINYINT(1) NOT NULL DEFAULT 0 AFTER `adminsettings`,
    CHANGE COLUMN `adminusers` `adminusers` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `admingroups` `admingroups` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `admincontent` `admincontent` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `adminother` TINYINT(1) NOT NULL DEFAULT 0 AFTER `admincontent`,
    ADD COLUMN `adminpages` TINYINT(1) NOT NULL DEFAULT 0 AFTER `adminother`,
    CHANGE COLUMN `adminsection` `adminsection` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `admincategory` `admincategory` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminbook` `adminbook` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminseparator` `adminseparator` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `admingallery` `admingallery` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminlink` `adminlink` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminforum` `adminforum` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminpluginpage` `adminpluginpage` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminart` `adminart` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminallart` `adminallart` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminchangeartauthor` `adminchangeartauthor` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminconfirm` `adminconfirm` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminpoll` `adminpoll` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminpollall` `adminpollall` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminsbox` `adminsbox` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminbox` `adminbox` TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN `adminhcm` VARCHAR(255) NOT NULL DEFAULT '' AFTER `fileadminaccess`,
    CHANGE COLUMN `adminhcmphp` `adminhcmphp` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminbackup` `adminbackup` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminmassemail` `adminmassemail` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `adminposts` `adminposts` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `changeusername` `changeusername` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `postcomments` `postcomments` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `unlimitedpostaccess` `unlimitedpostaccess` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `locktopics` `locktopics` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `stickytopics` `stickytopics` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `movetopics` `movetopics` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `artrate` `artrate` TINYINT(1) NOT NULL DEFAULT 0,
    CHANGE COLUMN `pollvote` `pollvote` TINYINT(1) NOT NULL DEFAULT 0,
    DROP COLUMN `adminrestore`,
    DROP COLUMN `adminbans`;