<?php

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

class AddLogTable extends AbstractMigration
{
    public function change()
    {
        $collation = ['collation' => 'utf8mb4_unicode_ci'];

        $table = $this->table('_log');

        $table
            ->addColumn('level', 'integer', ['limit' => 4])
            ->addColumn('category', 'string', ['limit' => 64] + $collation)
            ->addColumn('time', 'integer', ['limit' => MysqlAdapter::INT_BIG])
            ->addColumn('message', 'text', $collation)
            ->addColumn('method', 'string', ['limit' => 32, 'null' => true] + $collation)
            ->addColumn('url', 'string', ['limit' => 2048, 'null' => true] + $collation)
            ->addColumn('ip', 'string', ['limit' => 45, 'null' => true] + $collation)
            ->addColumn('user_agent', 'string', ['null' => true] + $collation)
            ->addColumn('user_id', 'integer', ['null' => true])
            ->addColumn('context', 'text', ['null' => true] + $collation)
            ->create();

        // change the type of autogenerated column id
        $table->changeColumn('id', 'string', ['limit' => 36, 'identity' => false] + $collation);

        $table
            ->addIndex(['level'])
            ->addIndex(['category'])
            ->addIndex(['time'])
            ->addIndex(['message'], ['limit' => 255])
            ->addIndex(['method'])
            ->addIndex(['url'], ['limit' => 255])
            ->addIndex(['ip'])
            ->addIndex(['user_id']);

        $table->update();
    }
}
